version: '3.8'
name: "filings-navigator"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle/
    environment:
      RAILS_ENV: development
      DATABASE_URL: "mysql2://instrumentl:instrumentl@db/filings_navigator"

  db:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'filings_navigator'
      MYSQL_USER: 'instrumentl'
      MYSQL_PASSWORD: 'instrumentl'
      MYSQL_ROOT_PASSWORD: 'root_container'
    volumes:
      - mysql:/var/lib/mysql

# Names our volume
volumes:
  mysql:
  node_modules:
  bundle:
