FROM node:16-alpine AS node
FROM ruby:3.1.3-alpine
RUN apk add --update --no-cache \
      build-base \
      curl \
      git \
      libffi-dev \
      yarn \
      wget \
      imagemagick \
      tzdata \
      mysql-dev \
      gcompat
RUN gem install foreman

# node:
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

# ruby

WORKDIR /app

CMD foreman start -f Procfile.dev
